# Generated by Django 4.0.4 on 2022-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=200, verbose_name='Токен_ID')),
                ('tg_chat_id', models.CharField(max_length=200, verbose_name='Чат_ID')),
                ('tg_text', models.TextField(verbose_name='Текст повідомлення')),
                ('tg_time', models.DateTimeField(auto_now=True, verbose_name='Час відправки')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
            },
        ),
    ]
