# Generated by Django 4.0.4 on 2022-06-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Ціна', 'verbose_name_plural': 'Ціни'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
    ]
