- name: Deploy the Application 
  hosts: app
  become: yes
  vars: 
    db_name: newAppDb
    mysql_user_name: newUserDb
    mysql_user_password: newPassDb
    git_repo: https://github.com/rotoro-cloud/Laravel-Real-Estate-Venue-Portal.git
  roles:
    - role: rotoro_cloud.mysql_role
    - role: nginx-php-fpm-role
    - role: estate-app-role
    - role: firewall-oneserver-deploy
